[pytest]
python_files = test_*.py
python_classes = Test*
python_functions = test_*

markers =
    ui: Запускает все Ui автотесты
    courses: Для тестов, связанных с курсами.
    regression: Для регрессионных тестов.
    registration:
    smoke:
    critical:
    slow:
